language: R
sudo: false
cache: packages
warnings_are_errors: true

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
 
notifications:
  email: wagnersantos.ufs@hotmail.com
    on_success: change
on_failure: change
